### ISSUE TITLE
no module named uber

### ISSUE THREAD

**Issue by QingWei2018** [vivangkumar/uberpy#2]
I am using python3.5.1 right now. I have installed uberpy using pip.
when I was trying to import uberpy module in python IDE
it gives me following trace back
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    import uberpy
  File "C:\Users\thean_000\AppData\Local\Programs\Python\Python35-32\lib\site-packages\uberpy__init__.py", line 8, in <module>
    from uber import Uber
ImportError: No module named 'uber'

please help me work it out!
I will be appreciated!

**Comment by vivangkumar** [comment]
Hello!

The library hasn't been updated in a long long time and I probably will not be working on this anymore.
However, you should be using `from uberpy import Uber`.

Hopefully this solves your issue.
